atomic:
  CV.cv_click:
    title: 이미지 클릭
    comment: 마우스(@{btn_type})(@{btn_model})이미지(@{input_data})(@{click_position})
    icon: click-image
    helpManual: 에서현재()창검색이미지, 에서창중클릭해당이미지.
    inputList:
      - key: input_data
        title: 이미지
        tip: 지원에서이미지라이브러리중선택또는선택이미지가져오기이미지요소
      - key: btn_type
        title: 마우스
        tip: ''
      - key: btn_model
        title: 클릭방식
        tip: ''
      - key: click_position
        title: 클릭위치
        tip: 선택마우스클릭위치
      - key: specified_position
        title: 위치 지정
        tip: ''
      - key: horizontal_move
        title: 가로 이동
        tip: ''
      - key: vertical_move
        title: 세로 이동
        tip: ''
      - key: match_similarity
        title: 매칭 정확도
        tip: 조회이미지및현재페이지의정도값(높이매칭 정확도로99%), 매칭테이블현재저장된 가져오기의이미지전체일의시가능매칭성공
      - key: move_type
        title: 마우스 이동 방식
        tip: ''
      - key: move_speed
        title: 마우스 속도
        tip: ''
      - key: wait_time
        title: 이미지 대기출력시간(초)
        tip: 초과경과해당시간중지대기, 로10초
    outputList: []
  CV.hover_image:
    title: 이미지 위로 마우스 이동
    comment: 마우스에서이미지(@{input_data})의(@{click_position})
    icon: mouse-hover-image
    helpManual: 에서현재()창검색이미지, 를마우스까지해당이미지의위치 지정위.
    inputList:
      - key: input_data
        title: 이미지
        tip: 지원에서이미지라이브러리중선택또는선택이미지가져오기이미지요소
      - key: click_position
        title: 위치
        tip: ''
      - key: specified_position
        title: 위치 지정
        tip: 구격식이미지, 지원선택구격식작업일개, 선택이면에서이미지의중위치
      - key: horizontal_move
        title: 가로 이동
        tip: ''
      - key: vertical_move
        title: 세로 이동
        tip: ''
      - key: match_similarity
        title: 매칭 정확도
        tip: 조회이미지및현재페이지의정도값(높이매칭 정확도로99%), 매칭테이블현재저장된 가져오기의이미지전체일의시가능매칭성공
      - key: move_type
        title: 마우스 이동 방식
        tip: ''
      - key: move_speed
        title: 마우스 속도
        tip: ''
      - key: wait_time
        title: 이미지 대기출력시간(초)
        tip: 초과경과해당시간중지대기, 로10초
    outputList: []
  CV.is_image_exist:
    title: 이미지 존재 여부
    comment: 이미지(@{input_data})에서현재(@{exist_type})
    icon: if-image-exists
    helpManual: 에서현재()창검색이미지, 여부존재함.
    inputList:
      - key: input_data
        title: 이미지
        tip: 지원에서이미지라이브러리중선택또는선택이미지가져오기이미지요소
      - key: exist_type
        title: 유형
        tip: 이미지존재함또는찾을 수 없습니다, 분실행코드내용
      - key: match_similarity
        title: 매칭 정확도
        tip: 조회이미지및현재페이지의정도값(높이매칭 정확도로99%), 매칭테이블현재저장된 가져오기의이미지전체일의시가능매칭성공
      - key: wait_time
        title: 이미지 대기시간(초)
        tip: 초과경과해당시간중지대기, 로10초
    outputList: []
  CV.wait_image:
    title: 이미지 대기
    comment: 이미지 대기(@{input_data})(@{wait_type})
    icon: wait-image
    helpManual: 대기이미지출력또는실패, 계속실행 흐름.
    inputList:
      - key: input_data
        title: 이미지
        tip: 지원에서이미지라이브러리중선택또는선택이미지가져오기이미지요소
      - key: wait_type
        title: 대기유형
        tip: 이미지 대기출력또는실패
      - key: wait_time
        title: 대기시간(초)
        tip: 초과경과해당시간중지대기, 로10초
      - key: match_similarity
        title: 매칭 정확도
        tip: 조회이미지및현재페이지의정도값(높이매칭 정확도로99%), 매칭테이블현재저장된 가져오기의이미지전체일의시가능매칭성공
    outputList:
      - key: image_wait_result
        title: 대기결과
        tip: 이미지여부출력/실패, 에서대기시간내부출력/실패로true, 반대로false
  CV.image_input:
    title: 이미지 입력란에 입력
    comment: 선택이미지입력란(@{input_data})으로(@{input_type})입력(@{input_content})
    icon: image-input-box
    helpManual: 클릭목록입력란의이미지, 입력내용
    inputList:
      - key: input_data
        title: 이미지
        tip: 지원에서이미지라이브러리중선택또는선택이미지가져오기이미지요소
      - key: input_type
        title: 입력방식
        tip: ''
      - key: input_content
        title: 입력내용
        tip: ''
      - key: simulate_flag
        title: 사람입력
        tip: ''
      - key: interval
        title: 입력
        tip: ''
      - key: match_similarity
        title: 매칭 정확도
        tip: ''
      - key: wait_time
        title: 이미지 대기출력시간(초)
        tip: 초과경과해당시간중지대기, 로10초
    outputList: []
options:
  BtnType:
    - value: left
      label: 왼쪽 버튼
    - value: middle
      label: 중
    - value: right
      label: 오른쪽 버튼
  BtnModel:
    - value: click
      label: 단일
    - value: double_click
      label: 더블클릭
  PositionType:
    - value: center
      label: 중
    - value: random
      label: 임의 위치
    - value: specific
      label: 위치 지정
  MoveType:
    - value: linear
      label: 직선
    - value: simulation
      label: 사람
    - value: teleportation
      label: 시
  Speed:
    - value: slow
      label: 느림
    - value: normal
      label: 보통
    - value: fast
      label: 빠름
  ExistType:
    - value: exist
      label: 존재함
    - value: not_exist
      label: 찾을 수 없습니다
  WaitType:
    - value: appear
      label: 이미지출력
    - value: disappear
      label: 이미지실패
  InputType:
    - value: text
      label: 문자입력
    - value: clip
      label: 잘라내기입력
  Simulate_flag:
    - value: 'yes'
      label: 예
    - value: 'no'
      label: 아니오