atomic:
  Script.process:
    title: 하위 프로세스 실행
    comment: 하위 프로세스 실행(@{process:하위 프로세스})
    icon: run-sub-process
    helpManual: ''
    inputList:
      - key: process
        title: 하위 프로세스 선택
        tip: 실행할 하위 프로세스를 선택합니다.
      - key: process_param
        title: 매개변수 입력
        tip: ''
    outputList:
      - key: process_res
        title: 프로세스 실행 결과
        tip: ''
  Script.module:
    title: Python 모듈 실행
    comment: Python 모듈 실행(@{content:Python모듈})
    icon: run-python-module
    helpManual: ''
    inputList:
      - key: content
        title: 선택Python모듈
        tip: ''
      - key: module_param
        title: 매개변수 입력
        tip: ''
    outputList:
      - key: program_script
        title: ''
        tip: ''
  Script.component:
    title: 실행컴포넌트
    comment: 실행컴포넌트(@{component:컴포넌트})
    icon: ''
    helpManual: ''
    inputList:
      - key: component
        title: 선택컴포넌트
        tip: ''
    outputList: []
options: {}