types:
  ExcelObj:
    desc: Excel 객체
    funcList:
      - key: ExcelObj.get_full_name
        funcDesc: 파일 위치
      - key: ExcelObj.get_row_count
        funcDesc: 가능사용행의행데이터
      - key: ExcelObj.get_first_free_row
        funcDesc: 일개가능사용행