# @format

atomic:
  Gui.keyboard:
    title: 키보드입력
    comment: 통신경과(@{keyboard_type})방식키보드입력(@{message})
    icon: keyboard-input
    helpManual: ''
    inputList:
      - key: keyboard_type
        title: 입력방식
        tip: >-
          통신입력: windows키보드메시지의방식입력;잘라내기입력: 가져오기잘라내기내용 붙여넣기입력;그룹합치기: 사용삽입키보드기호그룹합치기빠름입력;드라이버입력: 사용드라이버입력, 일사용네트워크비밀번호입력또는통신입력방식불가입력의
      - key: message
        title: 입력내용
        tip: ''
      - key: simulate_flag
        title: 사람입력
        tip: 사람방식키보드개입력문자, 로아니오
      - key: interval
        title: 입력
        tip: 입력, 단일위치로초
    outputList: []
  Gui.key_input:
    title: 키보드
    comment: 사용키보드(@{keys_str})(@{key_model})
    icon: keyboard-simulate-key
    helpManual: 통신경과키보드행입력
    inputList:
      - key: keys_str
        title: 그룹합치기
        tip: 그룹합치기
      - key: key_model
        title: 방식
        tip: 방식
    outputList: []
  Gui.mouse:
    title: 마우스클릭
    comment: 마우스(@{btn_type:왼쪽 버튼/오른쪽 버튼/중}) (@{btn_model:아래//단일기기/더블클릭}))
    icon: mouse-click
    helpManual: ''
    inputList:
      - key: btn_type
        title: 마우스
        tip: 선택클릭마우스위의위치
      - key: btn_model
        title: 클릭방식
        tip: 선택마우스의클릭방식
      - key: ctrl_type
        title: 키보드
        tip: 선택키보드, 로없음
    outputList: []
  Gui.mouse_wheel:
    title: 마우스
    comment: 마우스(@{scroll_type})(@{scroll_px||times}),방법로:(@{direction})
    icon: mouse-scroll-webpage
    helpManual: ''
    inputList:
      - key: scroll_type
        title: 방식
        tip: ''
      - key: times
        title: 지정데이터
        tip: 입력마우스의데이터,일거리로120개웹 페이지이미지
      - key: scroll_px
        title: 지정이미지
        tip: 입력지정이미지, 단일위치로px, 일로0-9999의데이터값
      - key: direction
        title: 방법
        tip: ''
      - key: ctrl_type
        title: 키보드
        tip: 선택키보드, 로없음
    outputList: []
  Gui.mouse_move:
    title: 마우스
    comment: 에서(@{window_type})위마우스까지(@{position_x}, @{position_y})
    icon: mouse-move
    helpManual: ''
    inputList:
      - key: window_type
        title: 창유형
        tip: 개화면: 으로화면왼쪽위역할로위치;창: 으로창왼쪽위역할로위치
      - key: window_position
        title: 창왼쪽위역할위치
        tip: ''
      - key: get_mouse_position
        title: 가져오기마우스위치
        tip: ''
      - key: position_x
        title: 마우스x위치
        tip: ''
      - key: position_y
        title: 마우스y위치
        tip: ''
      - key: move_type
        title: 마우스 이동 방식
        tip: 선택마우스 이동 방식
      - key: move_speed
        title: 마우스 속도
        tip: ''
    outputList: []
  Gui.mouse_move_new:
    title: 마우스
    comment: 에서(@{window_type})위마우스까지(@{position_x}, @{position_y})
    icon: mouse-move
    helpManual: ''
    inputList:
      - key: window_type
        title: 창유형
        tip: 개화면: 으로화면왼쪽위역할로위치;창: 으로창왼쪽위역할로위치
      - key: window_pick
        title: 창선택
        tip: 선택할의창
      - key: get_mouse_position
        title: 가져오기마우스위치
        tip: ''
      - key: position_x
        title: 마우스x위치
        tip: ''
      - key: position_y
        title: 마우스y위치
        tip: ''
      - key: move_type
        title: 마우스 이동 방식
        tip: 선택마우스 이동 방식
      - key: move_speed
        title: 마우스 속도
        tip: ''
    outputList: []
  Gui.mouse_drag:
    title: 마우스
    comment: >-
      마우스에서위치(@{start_pos_x}, @{start_pos_y})까지종료위치(@{end_pos_x},
      @{end_pos_y})
    icon: mouse-drag
    helpManual: ''
    inputList:
      - key: start_pos_x
        title: 마우스x위치
        tip: ''
      - key: start_pos_y
        title: 마우스y위치
        tip: ''
      - key: end_pos_x
        title: 마우스종료x위치
        tip: ''
      - key: end_pos_y
        title: 마우스종료y위치
        tip: ''
      - key: btn_type
        title: 마우스
        tip: 시아래의마우스위치
      - key: move_type
        title: 방식
        tip: 선택마우스 이동 방식
      - key: move_speed
        title: 정도
        tip: 선택마우스 속도
      - key: ctrl_type
        title: 키보드
        tip: 선택마우스시의키보드, 로없음
    outputList: []
  Gui.mouse_position:
    title: 가져오기마우스위치
    comment: 가져오기현재마우스위치출력(@{point_x}, @{point_y})
    icon: get-mouse-position
    helpManual: ''
    inputList: []
    outputList:
      - key: point_x
        title: 마우스x위치
        tip: ''
      - key: point_y
        title: 마우스y위치
        tip: ''
options:
  KeyboardType:
    - value: normal
      label: 통신입력
    - value: driver
      label: 드라이버입력
    - value: clip
      label: 입력
    - value: gblid
      label: ghost입력
  Simulate_flag:
    - value: 'yes'
      label: 예
    - value: 'no'
      label: 아니오
  KeyModel:
    - value: click
      label: 단일
    - value: down
      label: 아래
    - value: up
      label: 
  BtnType:
    - value: left
      label: 왼쪽 버튼
    - value: middle
      label: 중
    - value: right
      label: 오른쪽 버튼
  BtnModel:
    - value: click
      label: 단일
    - value: double_click
      label: 더블클릭
    - value: down
      label: 아래
    - value: up
      label: 
  ControlType:
    - value: none
      label: 없음
    - value: ctrl
      label: ctrl
    - value: alt
      label: alt
    - value: shift
      label: shift
    - value: win
      label: win
    - value: space
      label: space
  ScrollType:
    - value: time
      label: 데이터
    - value: px
      label: 이미지
  Direction:
    - value: up
      label: 위
    - value: down
      label: 아래
  WindowType:
    - value: fullscreen
      label: 개화면
    - value: active_window
      label: 창
  MoveType:
    - value: linear
      label: 직선
    - value: simulation
      label: 사람방식
    - value: teleportation
      label: 시
  Speed:
    - value: slow
      label: 느림
    - value: normal
      label: 보통
    - value: fast
      label: 빠름