/**
 * HTML tag labels shown in the Korean element picker.
 */
export const TagMap = {
  html: '문서',
  body: '본문',
  div: '영역',
  span: '인라인 영역',
  p: '문단',
  a: '링크',
  address: '주소',
  area: '이미지맵 영역',
  article: '문서 영역',
  audio: '오디오',
  b: '굵은 텍스트',
  button: '버튼',
  canvas: '캔버스',
  code: '코드 텍스트',
  col: '테이블 열',
  colgroup: '테이블 열 그룹',
  datalist: '데이터 목록',
  details: '상세 정보',
  dialog: '대화 상자',
  em: '강조 텍스트',
  embed: '외부 콘텐츠',
  footer: '푸터',
  form: '폼',
  frame: '프레임',
  h1: '제목',
  h2: '제목',
  h3: '제목',
  h4: '제목',
  h5: '제목',
  h6: '제목',
  header: '헤더',
  hr: '구분선',
  i: '기울임 텍스트',
  iframe: '인라인 프레임',
  img: '이미지',
  input: '입력',
  textarea: '여러 줄 입력',
  label: '설명',
  li: '목록',
  main: '본문 영역',
  mark: '강조 표시 텍스트',
  menu: '메뉴',
  nav: '내비게이션',
  ol: '순서 있는 목록',
  picture: '이미지',
  progress: '진행률',
  select: '드롭다운',
  summary: '요약',
  table: '테이블',
  tr: '테이블 행',
  td: '셀',
  ul: '순서 없는 목록',
  video: '비디오',
}
/**
 * Input type labels shown in the Korean element picker.
 */
export const InputTypeMap = {
  text: '입력란',
  password: '비밀번호',
  checkbox: '체크박스',
  radio: '라디오 버튼',
  submit: '제출 버튼',
  reset: '초기화 버튼',
  button: '버튼',
  file: '파일',
  hidden: '숨김 입력',
  image: '이미지',
  email: '이메일',
  url: 'URL',
  tel: '전화번호',
  number: '숫자',
  search: '검색',
  range: '범위',
  date: '날짜',
  time: '시간',
  month: '월',
  week: '주',
  datetime: '날짜 및 시간',
  color: '색상',
}
