TRUNCATE rpa.his_data_enum;
INSERT INTO rpa.his_data_enum (parent_code,icon,field,text,num,unit,percent,tip,`order`) VALUES
	 ('sourceData','icon-usercount','userNum','사용자데이터량',NULL,'개',NULL,'항목중회원가입의사용자항목데이터(아니오패키지항목사용 안 함상태아래의사용자)',0),
	 ('sourceData','icon-chanpin','terminal','단말데이터량',NULL,'개',NULL,'항목중항목의단말데이터량',1),
	 ('sourceData','icon-jiqiren','robotNum','봇데이터량',NULL,'개',NULL,'항목중모든완료발송버전의봇',2),
	 ('executeData','icon-zhenshikexin','executeSuccess','실행성공항목데이터',NULL,'항목',NULL,'항목중모든의봇실행성공의항목데이터',0),
	 ('executeData','icon-zhanbi','executeSuccessRate','실행성공항목',NULL,'%',NULL,'실행성공항목=성공항목데이터/(성공항목데이터+실패항목데이터+중중지항목데이터)',1),
	 ('executeData','icon-shijian','executeTimeTotalHour','항목계획실행시길이',NULL,'시간',NULL,'봇성공실행의항목시길이(아니오패키지항목정상에서실행, 실패, 중중지의시길이)',2),
	 ('executeData','icon-renyuan','laborSaveHour','항목계획항목사람항목',NULL,'사람/항목',NULL,'성공실행시길이(시간)/8(시간)8항목사람의항목',3),
	 ('robotExecuteToday','icon-todaycount','executeTotal','항목일실행항목데이터',NULL,NULL,NULL,'항목일실행항목데이터',0),
	 ('robotExecuteToday','icon-running','executeRunning','항목일정상에서실행',NULL,NULL,'항목{executeRunningRate}%','항목일정상에서실행',1),
	 ('robotExecuteToday','icon-zhenshikexin','executeSuccess','항목일실행성공',NULL,NULL,'항목{executeSuccessRate}%','항목일실행성공',2),
	 ('robotExecuteToday','icon-shibai','executeFail','항목일실행실패',NULL,NULL,'항목{executeFailRate}%','항목일실행실패',3),
	 ('robotExecuteToday','icon-zanting','executeAbort','항목일실행중중지',NULL,NULL,'항목{executeAbortRate}%','항목일실행중중지',4),
	 ('terminalRealTime','icon-chanpin','TerminalTotal','단말항목데이터',NULL,NULL,NULL,'항목의단말데이터량',0),
	 ('terminalRealTime','icon-manglu','busyNum','항목데이터',NULL,NULL,NULL,'정상에서실행의단말데이터량',1),
	 ('terminalRealTime','icon-kongxian','freeNum','빈항목데이터',NULL,NULL,NULL,'완료항목연결미완료실행의단말데이터량',2),
	 ('terminalRealTime','icon-lixian','offlineNum','항목데이터',NULL,NULL,NULL,'미완료연결의단말데이터량',3),
	 ('terminalDataOverview','icon-shijian','terminalTimeHour','실행시길이',NULL,'h',NULL,'성공실행의시길이',0),
	 ('terminalDataOverview','icon-zhenshikexin','terminalNum','실행성공항목데이터',NULL,NULL,NULL,'성공실행의항목데이터',1),
	 ('robotOverview','icon-todaycount','executeTotal','항목계획실행항목데이터',NULL,NULL,NULL,'항목계획실행항목데이터',0),
	 ('robotOverview','icon-zhenshikexin','executeSuccess','항목계획성공항목데이터',NULL,'항목','항목{executeSuccessRate}%','항목계획성공항목데이터',1),
	 ('robotOverview','icon-shibai','executeFail','항목계획실패항목데이터',NULL,'항목','항목{executeFailRate}%','항목계획실패항목데이터',2),
	 ('robotOverview','icon-zanting','executeAbort','항목계획중중지항목데이터',NULL,'항목','항목{executeAbortRate}%','항목계획중중지항목데이터',3),
	 ('robotExecutionData','icon-todaycount','executeTotal','실행항목데이터',NULL,NULL,NULL,'실행항목데이터',0),
	 ('robotExecutionData','icon-shijian','executeTimeHour','실행시길이',NULL,'시간',NULL,'실행시길이(아니오패키지항목정상에서실행, 실패, 중중지의시길이)',1),
	 ('robotExecutionData','icon-zhenshikexin','executeSuccess','실행성공',NULL,NULL,'항목{executeSuccessRate}%','실행성공항목데이터',2),
	 ('robotExecutionData','icon-shibai','executeFail','실행실패',NULL,NULL,'항목{executeFailRate}%','실행실패항목데이터',3),
	 ('robotExecutionData','icon-zanting','executeAbort','실행중중지',NULL,NULL,'항목{executeAbortRate}%','실행중중지항목데이터',4);