const mirrorList = [
  { value: 'https://pypi.org/simple', disabled: false },
]
const pythonLoadingMap = {
  installing: {
    closable: false,
    icon: 'installing.svg',
    loadingText: '설치 중입니다. 잠시만 기다려 주세요...',
    okBtn: false,
    cancleBtn: false,
  },
  installFail: {
    closable: false,
    icon: 'installFail.svg',
    loadingText: '설치에 실패했습니다.',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  installSuccess: {
    closable: false,
    icon: 'installSuccess.svg',
    loadingText: '설치되었습니다.',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  uninstalling: {
    closable: false,
    icon: 'uninstalling.svg',
    loadingText: '삭제 중입니다. 잠시만 기다려 주세요...',
    okBtn: false,
    cancleBtn: false,
  },
  uninstallFail: {
    closable: false,
    icon: 'uninstalling.svg',
    loadingText: '삭제에 실패했습니다.',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  uninstallSuccess: {
    closable: false,
    icon: 'uninstalling.svg',
    loadingText: '삭제되었습니다.',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  upgrading: {
    closable: false,
    icon: 'upgrading.svg',
    loadingText: '업그레이드 중입니다. 잠시만 기다려 주세요...',
    okBtn: false,
    cancleBtn: false,
  },
  upgradeFail: {
    closable: false,
    icon: 'upgrading.svg',
    loadingText: '업그레이드에 실패했습니다.',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  upgradeSuccess: {
    closable: false,
    icon: 'upgrading.svg',
    loadingText: '업그레이드되었습니다.',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  uninstallTip: {
    closable: true,
    headerText: '안내',
    icon: 'uninstalling.svg',
    loadingText: '이 패키지를 삭제하시겠습니까?',
    okBtn: true,
    okFn: 'uninstallPackage',
    cancleBtn: true,
  },
  upgradePythonTip: {
    closable: true,
    headerText: '안내',
    icon: 'upgradePythonPackage.svg',
    loadingText: '이 패키지를 새 버전으로 업그레이드하시겠습니까?',
    okBtn: true,
    okFn: 'upgradePackage',
    cancleBtn: true,
  },
}

export {
  mirrorList,
  pythonLoadingMap,
}
