atomic:
  Window.exist:
    title: 창 존재 여부
    comment: 선택창(@{pick})여부(@{check_type}), 예실행으로아래
    icon: check-window-exists
    helpManual: ''
    inputList:
      - key: pick
        title: 창선택
        tip: 선택할여부존재함의창객체
      - key: check_type
        title: 방식
        tip: 선택방식, 로존재함
      - key: wait_time
        title: 대기시간(초)
        tip: 대기 결과의시간
    outputList: []
  Window.top:
    title: 창
    comment: 창객체(@{pick})
    icon: pin-window
    helpManual: ''
    inputList:
      - key: pick
        title: 창선택
        tip: 선택할의창객체
    outputList: []
  Window.close:
    title: 창 닫기
    comment: 닫기 프로그램창객체(@{pick})
    icon: close-window
    helpManual: ''
    inputList:
      - key: pick
        title: 창선택
        tip: 선택할의창객체
    outputList: []
  Window.set_size:
    title: 창 크기 조정
    comment: 선택한 창 @{pick}의 크기를 @{size_type} 방식으로 조정합니다.
    icon: resize-window
    helpManual: ''
    inputList:
      - key: pick
        title: 창 선택
        tip: 크기를 조정할 프로그램 창을 선택합니다.
      - key: size_type
        title: 조정 방식
        tip: 지정 크기, 최대화, 최소화 중 선택합니다.
      - key: width
        title: 창 너비
        tip: 창 너비를 픽셀 단위로 입력합니다.
      - key: height
        title: 창 높이
        tip: 창 높이를 픽셀 단위로 입력합니다.
    outputList: []
options:
  WindowExistType:
    - value: exist
      label: 존재함
    - value: not_exist
      label: 찾을 수 없습니다
  WindowSizeType:
    - value: custom
      label: 지정
    - value: max
      label: 최대화
    - value: min
      label: 최소화
