atomic:
  Report.print:
    title: 로그 출력
    comment: 를변수(@{msg})인쇄
    icon: log-print
    helpManual: ''
    inputList:
      - key: report_type
        title: 로그유형
        tip: ''
      - key: msg
        title: 로그내용
        tip: 실행 중 출력할 로그 변수
    outputList: []
options:
  ReportLevelType:
    - value: info
      label: 정보
    - value: warning
      label: 경고
    - value: error
      label: 오류