export const BOOT = 'boot' // 시작
export const LOGIN = 'login' // 로그인
export const ARRANGE = 'arrange' // 정렬
export const DESIGNER = 'designer' // 계획기기
export const ACTUATOR = 'actuator' // 실행기기
export const APPLICATIONMARKET = 'applicationMarket'
export const AIASSISTANT = 'aiAssistant'
export const PROJECTMANAGEMENT = 'projectManagement' // 관리관리
export const COMPONENTMANAGEMENT = 'componentManagement' // 컴포넌트관리관리
export const COMPONENTCREATED = 'componentCreated' // 생성의컴포넌트
export const PROJECTCREATED = 'projectCreated' // 생성의
export const PROJECTMARKET = 'projectMarket' // 가져오기의
export const MODULEMANAGEMENT = 'moduleManagement' // 컴포넌트관리관리
export const TEMPLATEMANAGEMENT = 'templateManagement' // 관리관리
export const ROBOTLIST = 'robots' // 사용목록
export const EXCUTELIST = 'executionRecords' // 실행기록
export const TASKLIST = 'scheduleTasks' // 예약 작업
export const QUEUELIST = 'queueList' // 큐목록

export const SPARKDESKFLOW = 'flow' // 프로세스
export const SPARKDESKDATA = 'data'
export const SPARKDESKKNOW = 'book'
export const MARKETLIST = 'marketList'
export const MARKETMY = 'myPublic'
export const TEAMMARKETS = 'teamMarkets'
export const TEAMMARKETMANAGE = 'teamMarketManage'
export const OFFICIALMARKET = 'officialMarket'
export const APPLICATION = 'application'
export const RECOMMEND = 'recommendApp'
export const EDITORPAGE = 'editorPage'
export const SMARTCOMPONENT = 'smartComponent'
